name: Deploy Pelican site to GitHub Pages
on:
  workflow_call:
    inputs:
      settings:
        type: string
        default: "publishconf.py"
      output-path:
        type: string
        default: "output"
      cache:
        type: boolean
      cache-path:
        type: string
        default: "cache"
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Install requirements
        run: pip install "pelican[markdown]"
      - name: Print Pelican settings
        run: pelican --print-settings > .pelican_settings.json
        shell: bash
      - name: Cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ hashFiles('.pelican_settings.json') }}
          path: ${{ inputs.cache-path }}
        if:
          ${{ inputs.cache }}
      - name: Build Pelican site
        run: pelican --settings ${{ inputs.settings }} --extra-settings SITEURL='"${{ steps.pages.outputs.base_url }}"'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ inputs.output-path }}
  Deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

